### ISSUE TITLE
The definition of RobinsonFoulds() 

### ISSUE THREAD

**Issue by Cassie818** [ms609/TreeDist#117]
Hi there,

I’m a little bit confused about the function RobinsonFoulds(), and please forgive my ignorance. Is the function RobinsonFoulds() based on RobinsonFoulds (Robinson & Foulds, 1981), but corrected with phylogenetic information (Smith, 2020)? How does it differ from the MutualClusteringInfo() function?

**Comment by ms609** [comment]
Thanks for the question.

- `RobinsonFoulds()` calculates the distance of Robinson & Foulds, 1981.
- `InfoRobinsonFoulds()` gives the ‘information-corrected’ Robinson–Foulds (ICRF) similarity measure (§2.1 of [Smith 2020](https://doi.org/10.1093/bioinformatics/btaa614)).
- `MutualClusteringInfo()` is the distance I recommend using, it finds the optimal matching of splits that maximises the (clustering) information shared between two trees (§2.2 of Smith 2020).

I'll update the documentation to make this clearer from the manual page.

**Comment by Cassie818** [comment]
Thanks a lot!
