### ISSUE TITLE
Calculating adjusted R2 values from ClusteringInfoDistance() after randomization?

### ISSUE THREAD

**Issue by Jigyasa3** [ms609/TreeDist#65]
Hey @ms609 

Following up on the [issue44](https://github.com/ms609/TreeDist/issues/44), I am interested in calculating the goodness of fit and adjusted R2 value for `ClusteringInfoDistance()` value from a given pair of host and symbiont trees after 100,000 randomizations.

Any suggestion if it's possible?

**Comment by ms609** [comment]
Hi, I'm afraid I'm not quite sure that I understand your question: what distribution would you be testing fit against, and what variables would you be regressing?

Cheers,

Martin

**Comment by ms609** [comment]
Closing this issue as I never understood quite what was being asked.  Feel free to re-open if you are able to elaborate on the comment.
