### ISSUE TITLE
When no. of tips in species tree and gene tree dont match. Adding new tips to the species tree

### ISSUE THREAD

**Issue by Jigyasa3** [ms609/TreeDist#97]
Hi @ms609 ,

Thanks again for a great package! I am trying to run TreeDist on species tree-gene tree pair where there are multiple no. of tips in the gene tree per species.

I found the [add_host_tips.R](https://github.com/BPerezLamarque/HOME/blob/master/tutorial_HOME/add_host_tips.R) script to help add new tips of zero branch length to the species tree. 
But it only seems to work for a specific version of the species tree (generated from BEAST2 output) but not from IQTREE or FASTTREE. For the IQTREE and FASTREE versions of the species tree, the script generates a tree with all branch lengths equal to zero.

I was wondering if there is a workaround for this problem in TreeDist? Will it work if the no. of tips in two trees are unequal?

Regards,
Jigyasa

**Comment by ms609** [comment]
Dear Jigyasa,

I have been working on implementing the comparison of trees with different tips – see #92.  As far as I can tell this works, but I need to find a few hours to fully test and document the new functions.

In the meantime you can access the code at 
https://github.com/ms609/TreeDist/tree/differentTips

or install with Try `devtools::install_github("ms609/TreeDist@differentTips")`

**Comment by ms609** [comment]
This code is now on its way to CRAN as version 2.6.0; hopefully it addresses your issue.  Do re-open the thread if not!
